remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: azure-ad-license-status
description: Creates an Azure AD license report based on license assignments and consumption
show_downloads: false
